version: '3.9'

services:
  nginx:
    build: ./nginx
    image: ${REGISTRY_HOST}/pyperf-nginx:${VERSION}
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.STACK_NAME-http.rule=Host(`pyperf.cssnr.com`)"
        - "traefik.http.routers.STACK_NAME-http.entrypoints=http"
        - "traefik.http.routers.STACK_NAME-http.middlewares=https-redirect"
        - "traefik.http.routers.STACK_NAME-https.rule=Host(`pyperf.cssnr.com`)"
        - "traefik.http.routers.STACK_NAME-https.entrypoints=https"
        - "traefik.http.routers.STACK_NAME-https.tls=true"
        - "traefik.http.services.STACK_NAME.loadbalancer.server.port=80"
        - "traefik.http.services.STACK_NAME.loadbalancer.server.scheme=http"
    volumes:
      - app_data:/data
    secrets:
      - source: cssnr_basic_http_auth
        target: /etc/nginx/auth.users
    networks:
      - traefik-public
      - net-internal
    depends_on:
      - app
      - flower
      - redis-commander
      - phpmyadmin

  pyperf3:
    build: ./pyperf3
    image: ${REGISTRY_HOST}/pyperf3:${VERSION}
    env_file: settings.env
    command: "python3 pyperf3.py"
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.tcp.routers.STACK_NAME-tcp.entrypoints=tcp"
        - "traefik.tcp.services.STACK_NAME-tcp.loadbalancer.server.port=5201"
        - "traefik.tcp.routers.STACK_NAME-udp.entrypoints=tcp"
        - "traefik.tcp.services.STACK_NAME-udp.loadbalancer.server.port=5201"
    networks:
      - traefik-public
      - net-internal

  app:
    build: ./app
    image: ${REGISTRY_HOST}/pyperf-app:${VERSION}
    env_file: settings.env
    command: "gunicorn pyperf.asgi:application -b 0.0.0.0:9000 -w 4 -k uvicorn.workers.UvicornWorker"
    deploy:
      mode: global
    volumes:
      - app_data:/data
    networks:
      - net-internal
    depends_on:
      - redis

  worker:
    image: ${REGISTRY_HOST}/pyperf-app:${VERSION}
    env_file: settings.env
    command: "celery -A pyperf worker -l INFO -c 2"
    deploy:
      replicas: 1
    networks:
      - net-internal
    depends_on:
      - app
      - redis

  beat:
    image: ${REGISTRY_HOST}/pyperf-app:${VERSION}
    env_file: settings.env
    command: "celery -A pyperf beat -l INFO -S django"
    deploy:
      replicas: 1
    networks:
      - net-internal
    depends_on:
      - app
      - redis

  redis:
    image: redis:6-alpine
    command: "redis-server --appendonly yes"
    deploy:
      replicas: 1
    networks:
      - net-internal
    volumes:
      - redis_data:/data

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379:0,local:redis:6379:1
      - URL_PREFIX=/redis
      - TRUST_PROXY=true
    deploy:
      replicas: 1
    networks:
      - net-internal
    depends_on:
      - redis

  flower:
    image: mher/flower:1.2
    env_file: settings.env
    deploy:
      replicas: 1
    volumes:
      - flower_data:/data
    networks:
      - net-internal
    depends_on:
      - app
      - redis
      - worker

  phpmyadmin:
    image: phpmyadmin:latest
    env_file: settings.env
    environment:
      APACHE_PORT: 8082
      PMA_ABSOLUTE_URI: /phpmyadmin/
      PMA_HOST: ${DATABASE_HOST}
      PMA_PORT: ${DATABASE_PORT}
      PMA_USER: ${DATABASE_USER}
      PMA_PASSWORD: ${DATABASE_PASS}
    deploy:
      replicas: 1
    networks:
      - net-internal

secrets:
  cssnr_basic_http_auth:
    external: true

volumes:
  app_data:
  flower_data:
  redis_data:

networks:
  traefik-public:
    external: true
  net-internal:
    driver: overlay
